CREATE TABLE "GAB_5946_GST_LOG"(
 "ID" IDENTITY,
 "PERIOD" TINYINT NOT NULL,
 "FISCAL_YR" SMALLINT NOT NULL,
 "REV" SMALLINT NOT NULL,
 "USERID" VARCHAR(8) NOT NULL,
 "DATE_TIME_CHANGED" DATETIME NOT NULL,
 PRIMARY KEY ("ID"));
