CREATE TABLE "GAB_5946_GST_RETURN"(
 "PERIOD" TINYINT NOT NULL,
 "FISCAL_YR" SMALLINT NOT NULL,
 "SALES" NUMERIC(16,2),
 "ZR_AR" NUMERIC(16,2),
 "NZZER_AR" NUMERIC(16,2),
 "GST_AR" NUMERIC(16,2),
 "ADJ_AR" NUMERIC(16,2),
 "PURCHASE" NUMERIC(16,2),
 "ADJ_AP" NUMERIC(16,2),
 "GST_AP" NUMERIC(16,2),
 PRIMARY KEY ("PERIOD","FISCAL_YR"));