CREATE TABLE "GAB_5946_GST_DATA"(
 "BATCH" CHAR(5),
 "LINE" NUMERIC(5,0),
 "POST_DATE_SQL" DATE,
 "TAX_ZONE" CHAR(2) NOT NULL,
 "TAX_AUTHORITY" CHAR(3) NOT NULL,
 "REFERENCE" VARCHAR(30),
 "BASE_AMOUNT" NUMERIC(16,2) NOT NULL,
 "TAX_AMOUNT" NUMERIC(16,2) NOT NULL,
 PRIMARY KEY ("BATCH","LINE","POST_DATE_SQL"));